# Secrets for the AWS thing
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.aws.keyid }}
    aws_secret_access_key = {{ .Values.aws.secretkey }}
---
{{ if or .Values.image.registry.username .Values.image.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secrets
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >
    {
      "auths": {
        {{ .Values.image.registry.hostname | quote }}: {
          "username": {{ .Values.image.registry.username | quote }},
          "password": {{ .Values.image.registry.password | quote }},
          "auth": {{ printf "%s:%s" .Values.image.registry.username .Values.image.registry.password | b64enc | quote }}
        }
      }
    }
{{ end }}
